PCA processor: filter by gene
Removed proc.progress at the end of processor

diff --git a/resolwe_bio/processes/pca.yml b/resolwe_bio/processes/pca.yml
--- a/resolwe_bio/processes/pca.yml
+++ b/resolwe_bio/processes/pca.yml
@@ -4,7 +4,7 @@
 ---
 
 - name: pca:1-0-0
-  version: 1.0.1
+  version: 1.0.2
   label: PCA
   type: data:pca
   category: analyses
@@ -12,10 +12,15 @@
   description: >
     Principal component analysis (PCA)
   input:
-    - name: expressions
+    - name: exps
       label: Expressions
       type: list:data:expression
       required: true
+    - name: genes
+      label: Filter genes
+      type: list:basic:string
+      required: false
+      default: ['NM_007659', 'NM_183417', 'NM_009870', 'NM_007668', 'NM_009873', 'NM_009874', 'NM_153599']
   output:
     - name: pca
       label: PCA
@@ -35,17 +40,22 @@
     bash: |
       . {{proc.slugs_path}}/venv-gencloud-0.1/bin/activate
 
-      {% for exp in expressions %}
+      EXPSET_TYPE="{{exps.0.output.exp_type}}"
+
+      {% for e in exps %}
+        {% if exps.0.output.exp_type != e.output.exp_type %}
+          echo "{\"proc.error\":\"Expressions must be of the same expression type\"}"
+        {% endif %}
+      {% endfor %}
+
+      {% for exp in exps %}
         exp=$exp"{{ exp.output.exp.file }},"
         obj_id=$obj_id"{{ exp.id }},"
       {% endfor %}
 
       echo "{\"proc.progress\":0.1, \"proc.rc\":$?}"
-
       obj_id=${obj_id%?}
       exp=${exp%?}
-
       echo "{\"proc.progress\":0.2,\"proc.rc\":$?}"
-
-      python -u {{ proc.slugs_path }}/gencloud-20131109/pca.py ${exp} ${obj_id}
-      echo "{\"proc.progress\":1.0,\"proc.rc\":$?}"
+      python -u {{ proc.slugs_path }}/gencloud-20131109/pca.py ${exp} ${obj_id} {% if genes %}--genes {% for g in genes %}"{{g}}" {% endfor %}{% endif %}
+      echo "{\"proc.rc\":$?}"
